version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    networks:
      - backend

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - backend

  comments:
    build:
      context: ./comments
      dockerfile: Dockerfile
    networks:
      - backend

  files:
    build:
      context: ./files
      dockerfile: Dockerfile
    networks:
      - backend

  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    networks:
      - backend

  notifications:
    build:
      context: ./notifications
      dockerfile: Dockerfile
    networks:
      - backend

  projects:
    build:
      context: ./projects
      dockerfile: Dockerfile
    networks:
      - backend

  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    networks:
      - backend

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    networks:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: <DB_PASSWORD>
      MYSQL_DATABASE: task_management
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  db_data:
