name: Auth Service Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Check for changes in 'auth/' directory
    - uses: dorny/paths-filter@v3
      id: check-changes
      with:
        filters: |
          auth:
            - 'auth/**'

    # Conditionally run Maven tests based on changes
    - name: Run Maven tests if changes are detected in 'auth/'
      if: steps.check-changes.outputs.auth == 'true'
      run: mvn -f auth/pom.xml clean test
